name: 'ALT Linux Image Builder'
description: 'Builder of ALT Linux images'
inputs:
  image:
    description: 'Image name (like live-rescue.iso)'
    required: true
    default: 'live-rescue.iso'
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Install podman
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Pull alt-builder image
      shell: bash
      run: |
        sudo podman pull ghcr.io/nisel11/alt-builder:latest

    - name: Run container
      shell: bash
      run: |
        sudo podman run -d --privileged \
          --systemd=always \
          --cap-add=ALL \
          --name alt-builder \
          --tmpfs /run \
          --tmpfs /run/lock \
          -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
          -v "${{ github.workspace }}:/workspace" \
          ghcr.io/nisel11/alt-builder:latest

    - name: Fix /workspace permission
      shell: bash
      run: |
        sudo podman exec alt-builder chown -R builder:builder /workspace
        sudo podman exec alt-builder chmod -R u+w /workspace

    - name: Build image
      shell: bash
      run: |
        sudo podman exec alt-builder su - builder -c \
          "cd ~ && \
          git clone https://github.com/${{ github.repository }} mkimage-profiles && \
          cd mkimage-profiles && \
          make \
          IMAGEDIR="/workspace/out" \
          BUILDLOG="/workspace/out/build.log" \
          ${{ inputs.image }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.image }}
        path: ${{ github.workspace }}/out/
        if-no-files-found: error
