name: Build and Push alt-builder Image

on:
  push:
    branches: [ main ]
  pull_request:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Install Podman
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build alt-builder image
        shell: bash
        run: |
          sudo podman build -t ${{ env.IMAGE_REGISTRY }}/alt-builder:latest .

      - name: Push alt-builder image to GHCR
        shell: bash
        run: |
          sudo podman push ${{ env.IMAGE_REGISTRY }}/alt-builder:latest
