name: Example building

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: nisel11/alt-image-builder@latest
        with:
          image: "regular-gnome.iso"